### PR TITLE
Add support for forwarding subscription to queue

### PR DESCRIPTION
**Pull request by daanl**
Hi,

Would be nice if you can accept this change, the change allows to add ForwardTo which is used by libraries like Masstransit

### CODE REVIEW

**Comment by Mossharbor** [comment]
Cool thanks for the addition I will take a look at this over the weekend.

**Comment by daanl** [comment]
Nice thanks!

**Review by Mossharbor — CHANGES_REQUESTED** [review]
Looks good.  I noticed that your changes to TestGetSubscriptions don't actually test that things are getting forwarded.  Did you confirm this another way?

**Comment by daanl** [comment]
@Mossharbor You can't create a ForwardTo if:

* Address is not valid (not existing)
* No access to it, thats why second header is there

If you specify on or other wrong you get and error server side and can't create the subscription

**Comment by Mossharbor** [comment]
Thanks for the changes!!  They should be in the *.13 package published now.

**Pull request merged**
